name = "CJ Loot Chests Backpacks Add-on";
picture = "CJ_LootChests_Backpacks_Addon/icons/icon.paa";
logoSmall = "CJ_LootChests_Backpacks_Addon/icons/icon_ss.paa";
logo = "CJ_LootChests_Backpacks_Addon/icons/icon_s.paa";
logoOver = "CJ_LootChests_Backpacks_Addon/icons/icon_s.paa";
tooltip = "$STR_CJ_LootChests_Backpacks_Addon_mod_name";
overview = "$STR_CJ_LootChests_Backpacks_Addon_mod_overview";
action = "https://steamcommunity.com/sharedfiles/filedetails/?id=2994594944";
author = "ataribaby";
version = "1.3";